# Site settings
title: Blog
description: "Second Year Engineering Student in Universidade do Minho"
url: "https://zepedroresende@github.com"
author:
  name: "Ze Pedro Resende"
  email: "j.p.resende68@gmail.com"
  url: "https://zepedroresende@github.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
